########### M3 CONFIG ######################
factory_rt_libs:
  - /home/meka/mekabot/m3meka/ros/m3ros_control/lib/libm3ros_control.so

rt_components:
  m3ros_control:
      m3ros_control_component: ros_control_component


