# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import component_base_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='ros_control_component.proto',
  package='',
  serialized_pb='\n\x1bros_control_component.proto\x1a\x14\x63omponent_base.proto\"8\n\x19RosControlComponentStatus\x12\x1b\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\r.M3BaseStatus\"\x1a\n\x18RosControlComponentParam\"\x1c\n\x1aRosControlComponentCommandB\x02H\x01')




_ROSCONTROLCOMPONENTSTATUS = descriptor.Descriptor(
  name='RosControlComponentStatus',
  full_name='RosControlComponentStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='base', full_name='RosControlComponentStatus.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=53,
  serialized_end=109,
)


_ROSCONTROLCOMPONENTPARAM = descriptor.Descriptor(
  name='RosControlComponentParam',
  full_name='RosControlComponentParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=111,
  serialized_end=137,
)


_ROSCONTROLCOMPONENTCOMMAND = descriptor.Descriptor(
  name='RosControlComponentCommand',
  full_name='RosControlComponentCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=139,
  serialized_end=167,
)

_ROSCONTROLCOMPONENTSTATUS.fields_by_name['base'].message_type = component_base_pb2._M3BASESTATUS
DESCRIPTOR.message_types_by_name['RosControlComponentStatus'] = _ROSCONTROLCOMPONENTSTATUS
DESCRIPTOR.message_types_by_name['RosControlComponentParam'] = _ROSCONTROLCOMPONENTPARAM
DESCRIPTOR.message_types_by_name['RosControlComponentCommand'] = _ROSCONTROLCOMPONENTCOMMAND

class RosControlComponentStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ROSCONTROLCOMPONENTSTATUS
  
  # @@protoc_insertion_point(class_scope:RosControlComponentStatus)

class RosControlComponentParam(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ROSCONTROLCOMPONENTPARAM
  
  # @@protoc_insertion_point(class_scope:RosControlComponentParam)

class RosControlComponentCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ROSCONTROLCOMPONENTCOMMAND
  
  # @@protoc_insertion_point(class_scope:RosControlComponentCommand)

# @@protoc_insertion_point(module_scope)
