  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Mode controllers used to switch between control methods ----------------------------
  position_joint_mode_controller:
    type: joint_mode_controller/JointModeController
    joint_mode: 1 # position

  velocity_joint_mode_controller:
    type: joint_mode_controller/JointModeController
    joint_mode: 2 # velocity


  # Position only controllers ----------------------------------------------
  right_position_controller:
    type: "position_controllers/JointPositionController"
    joints:
      - right_arm_j0
      - right_arm_j1
      - right_arm_j2
      - right_arm_j3
      - right_arm_j4
      - right_arm_j5
      - right_arm_j6

  left_position_controller:
    type: "position_controllers/JointPositionController"
    joints:
      - left_arm_j0
      - left_arm_j1
      - left_arm_j2
      - left_arm_j3
      - left_arm_j4
      - left_arm_j5
      - left_arm_j6

  # Position - Right and Left Joint Position Trajectory Controllers -------------------
  left_position_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - left_arm_j0
      - left_arm_j1
      - left_arm_j2
      - left_arm_j3
      - left_arm_j4
      - left_arm_j5
      - left_arm_j6

    constraints:
      goal_time: 0.0                   # Defaults to zero
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      left_arm_j0:
        trajectory: 0 
        goal: 0.1       
      left_arm_j1:
        trajectory: 0 
        goal: 0.1       
      left_arm_j2:
        trajectory: 0 
        goal: 0.1       
      left_arm_j3:
        trajectory: 0 
        goal: 0.1       
      left_arm_j4:
        trajectory: 0 
        goal: 0.1       
      left_arm_j5:
        trajectory: 0 
        goal: 0.1       
      left_arm_j6:
        trajectory: 0 
        goal: 0.1       

    state_publish_rate:  50 # Defaults to 50
    action_monitor_rate: 20 # Defaults to 20
    #hold_trajectory_duration: 0 # Defaults to 0.5

  right_position_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - right_arm_j0
      - right_arm_j1
      - right_arm_j2
      - right_arm_j3
      - right_arm_j4
      - right_arm_j5
      - right_arm_j6

    constraints:
      goal_time: 0.0                   
      stopped_velocity_tolerance: 0.01 
      right_arm_j0:
        trajectory: 0 
        goal: 0.1       
      right_arm_j1:
        trajectory: 0 
        goal: 0.1       
      right_arm_j2:
        trajectory: 0 
        goal: 0.1       
      right_arm_j3:
        trajectory: 0 
        goal: 0.1       
      right_arm_j4:
        trajectory: 0 
        goal: 0.1       
      right_arm_j5:
        trajectory: 0 
        goal: 0.1       
      right_arm_j6:
        trajectory: 0 
        goal: 0.1       

    state_publish_rate:  50 # Defaults to 50
    action_monitor_rate: 20 # Defaults to 20
    #hold_trajectory_duration: 0 # Defaults to 0.5

  # Velocity - Right and Left Joint Velocity Trajectory Controllers -------------------
  left_velocity_trajectory_controller:
    type: "velocity_controllers/JointTrajectoryController"
    joints:
      - left_arm_j0
      - left_arm_j1
      - left_arm_j2
      - left_arm_j3
      - left_arm_j4
      - left_arm_j5
      - left_arm_j6

    constraints:
      goal_time: 2.0                   # Defaults to zero
      stopped_velocity_tolerance: 0.4 # Defaults to 0.01
      left_arm_j0:
        trajectory: 0 
        goal: 0.2       
      left_arm_j1:
        trajectory: 0 
        goal: 0.2       
      left_arm_j2:
        trajectory: 0 
        goal: 0.2       
      left_arm_j3:
        trajectory: 0 
        goal: 0.2       
      left_arm_j4:
        trajectory: 0 
        goal: 0.2       
      left_arm_j5:
        trajectory: 0 
        goal: 0.2       
      left_arm_j6:
        trajectory: 0 
        goal: 0.2       

    gains:
      left_arm_j0: {p: 2.0,  i: 0.01, d: 1.0, i_clamp: 1}
      left_arm_j1: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}
      left_arm_j2: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}
      left_arm_j3: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}
      left_arm_j4: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}
      left_arm_j5: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}
      left_arm_j6: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}

    state_publish_rate:  50 # Defaults to 50
    action_monitor_rate: 20 # Defaults to 20
    #hold_trajectory_duration: 0 # Defaults to 0.5

  right_velocity_trajectory_controller:
    type: "velocity_controllers/JointTrajectoryController"
    joints:
      - right_arm_j0
      - right_arm_j1
      - right_arm_j2
      - right_arm_j3
      - right_arm_j4
      - right_arm_j5
      - right_arm_j6

    constraints:
      goal_time: 3.0                   
      stopped_velocity_tolerance: 0.04
      right_arm_j0:
        trajectory: 0 
        goal: 0.2       
      right_arm_j1:
        trajectory: 0 
        goal: 0.2       
      right_arm_j2:
        trajectory: 0 
        goal: 0.2       
      right_arm_j3:
        trajectory: 0 
        goal: 0.2       
      right_arm_j4:
        trajectory: 0 
        goal: 0.2       
      right_arm_j5:
        trajectory: 0 
        goal: 0.2       
      right_arm_j6:
        trajectory: 0 
        goal: 0.2       

    gains:
      right_arm_j0: {p: 2.0,  i: 0.01, d: 1.0, i_clamp: 1}
      right_arm_j1: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}
      right_arm_j2: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}
      right_arm_j3: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}
      right_arm_j4: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}
      right_arm_j5: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}
      right_arm_j6: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}

    state_publish_rate:  50 # Defaults to 50
    action_monitor_rate: 20 # Defaults to 20
    #hold_trajectory_duration: 0 # Defaults to 0.5
